use customer_analysis;
select * from customer_behaviour_analysis;

-- 1. Which category generates highest revenue?

select category, round(sum(purchase_amount),2) as highest_revenue
from  customer_behaviour_analysis
group by category
order by highest_revenue desc;

-- 2. Are discount actually increase purchase value?

select discount_applied, round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by discount_applied
order by total_revenue desc;

-- 3. What is the total revenue generated by male and female category?

select gender, round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by gender
order by total_revenue desc;

-- 4. Which customer used a discount but still spend more than average purchase amount

select avg(purchase_amount) from customer_behaviour_analysis;

select
 customer_id, discount_applied, purchase_amount
from customer_behaviour_analysis
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_behaviour_analysis)
order by purchase_amount asc
limit 10;

-- 5. Which are the top/bottom  5 products with highest average review rating?

select item_purchased, round(avg(review_rating),2) as avg_rating
from customer_behaviour_analysis
group by item_purchased
order by avg_rating desc
limit 5;

select item_purchased, round(avg(review_rating),2) as avg_rating
from customer_behaviour_analysis
group by item_purchased
order by avg_rating asc
limit 5;

-- 6. Average purchase: Standard vs Express Shipping

select shipping_type, count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase,
round(sum(purchase_amount),2) as total_amount
from customer_behaviour_analysis
-- where shipping_type in ('Standard','Express')
group by shipping_type;

-- 7. Do subscribed customers spend more?, compare avg spend and total revenew between subscribers and non subscribers

select subscription_status, count(distinct customer_id) as users, round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_spend
from customer_behaviour_analysis
group by subscription_status
order by total_spend desc;

-- 8. Top 5 products with highest discount usage

select item_purchased,
count(item_purchased) as total_no_of_times_sold,
count(case when discount_applied = 'Yes' then 1 end) as total_no_of_times_sold_when_discount_applied,
count(case when discount_applied = 'Yes' then 1 end)*100/count(*) as discount_percentage
from customer_behaviour_analysis
group by item_purchased
order by discount_percentage desc
limit 5;

-- 9. Segment customer into new, returnig and loyal based on their previous purchase
-- And show the count of each segment

select 
	case 
		when previous_purchases = '0' then 'New Customer'
		when previous_purchases  between 1 and 15 then 'Returning Customer'
	else 'Loyal Customer'
End as customer_segment,
count(*) as customer_count
from customer_behaviour_analysis
group by 
  	case 
		when previous_purchases = '0' then 'New Customer'
		when previous_purchases  between 1 and 15 then 'Returning Customer'
	else 'Loyal Customer'
End;

-- 10. Top 3 purchased products in each category
with cte as
(
select category, item_purchased, count(item_purchased) as most_purchased,
rank() over(partition by category order by count(item_purchased) desc) as rnk
from customer_behaviour_analysis
group by category, item_purchased
)
select * from cte
where rnk <=3;

-- 12. Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?

select
	case
		when previous_purchases > 5 then 'Repeat Buyers'
    Else 'Normal Buyers'
end as customer_type,
count(*) as customer_count,
subscription_status,
count(*)*100.0/ sum(count(*)) over(partition by case
												when previous_purchases > 5 then 'Repeat Buyers'
												Else 'Normal Buyers'
											end) as percent
from customer_behaviour_analysis
group by 
	case
		when previous_purchases > 5 then 'Repeat Buyers'
    Else 'Normal Buyers'
end,subscription_status ;

-- 12. What is the revenue contribution of each age group?

select
	case
		when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 50 then '36-50'
    else '51+'
end as age_group,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by
case
		when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 50 then '36-50'
    else '51+'
end
order by total_revenue desc;